package org.shirdrn.tinyframework.proxy.database.dao.impl;

import com.ibatis.common.util.PaginatedList;
import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import com.ibatis.sqlmap.client.event.RowHandler;
import com.ibatis.sqlmap.engine.execution.BatchException;

import java.sql.SQLException;
import java.util.List;
import org.shirdrn.tinyframework.proxy.database.dao.ProxyDatumDAO;
import org.shirdrn.tinyframework.proxy.database.model.ProxyDatum;
import org.shirdrn.tinyframework.proxy.database.model.ProxyDatumExample;

public class ProxyDatumDAOImpl extends SqlMapDaoTemplate implements ProxyDatumDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public ProxyDatumDAOImpl(DaoManager daoManager) {
		super(daoManager);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public int countByExample(ProxyDatumExample example) {
		Integer count = (Integer) queryForObject(
				"proxy_datum.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public int deleteByExample(ProxyDatumExample example) {
		int rows = delete("proxy_datum.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public int deleteByPrimaryKey(Integer id) {
		ProxyDatum key = new ProxyDatum();
		key.setId(id);
		int rows = delete("proxy_datum.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public Integer insert(ProxyDatum record) {
		Object newKey = insert("proxy_datum.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public Integer insertSelective(ProxyDatum record) {
		Object newKey = insert("proxy_datum.ibatorgenerated_insertSelective",
				record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<ProxyDatum> selectByExample(ProxyDatumExample example) {
		List<ProxyDatum> list = queryForList(
				"proxy_datum.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public ProxyDatum selectByPrimaryKey(Integer id) {
		ProxyDatum key = new ProxyDatum();
		key.setId(id);
		ProxyDatum record = (ProxyDatum) queryForObject(
				"proxy_datum.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public int updateByExampleSelective(ProxyDatum record,
			ProxyDatumExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = update(
				"proxy_datum.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public int updateByExample(ProxyDatum record, ProxyDatumExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = update("proxy_datum.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public int updateByPrimaryKeySelective(ProxyDatum record) {
		int rows = update(
				"proxy_datum.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public int updateByPrimaryKey(ProxyDatum record) {
		int rows = update("proxy_datum.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	private static class UpdateByExampleParms extends ProxyDatumExample {
		private Object record;

		public UpdateByExampleParms(Object record, ProxyDatumExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public int delete(String arg0) throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public List executeBatchDetailed() throws SQLException, BatchException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Object insert(String arg0) throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List queryForList(String arg0) throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List queryForList(String arg0, int arg1, int arg2)
			throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Object queryForObject(String arg0) throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public PaginatedList queryForPaginatedList(String arg0, int arg1)
			throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void queryWithRowHandler(String arg0, RowHandler arg1)
			throws SQLException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public int update(String arg0) throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}
}