SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE PROXY_DATUM;




/* Create Tables */

CREATE TABLE PROXY_DATUM
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
	HOST VARCHAR(255) NOT NULL,
	PORT INT NOT NULL,
	USER VARCHAR(255),
	PASSWORD VARCHAR(255),
	SUCCESS_COUNT INT DEFAULT 0,
	FAILURE_COUNT INT DEFAULT 0,
	STATUS INT DEFAULT 0,
	CREATED_AT DATE NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT idx_uni_host_port UNIQUE (HOST, PORT)
);



