package org.shirdrn.tinyframework.proxy.database.model;

import java.util.Date;

public class ProxyDatum {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column proxy_datum.ID
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column proxy_datum.HOST
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	private String host;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column proxy_datum.PORT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	private Integer port;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column proxy_datum.USER
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	private String user;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column proxy_datum.PASSWORD
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	private String password;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column proxy_datum.SUCCESS_COUNT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	private Integer successCount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column proxy_datum.FAILURE_COUNT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	private Integer failureCount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column proxy_datum.STATUS
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	private Integer status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column proxy_datum.CREATED_AT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	private Date createdAt;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column proxy_datum.UPDATED_AT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	private Date updatedAt;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column proxy_datum.ID
	 * @return  the value of proxy_datum.ID
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column proxy_datum.ID
	 * @param id  the value for proxy_datum.ID
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column proxy_datum.HOST
	 * @return  the value of proxy_datum.HOST
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public String getHost() {
		return host;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column proxy_datum.HOST
	 * @param host  the value for proxy_datum.HOST
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public void setHost(String host) {
		this.host = host;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column proxy_datum.PORT
	 * @return  the value of proxy_datum.PORT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public Integer getPort() {
		return port;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column proxy_datum.PORT
	 * @param port  the value for proxy_datum.PORT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public void setPort(Integer port) {
		this.port = port;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column proxy_datum.USER
	 * @return  the value of proxy_datum.USER
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public String getUser() {
		return user;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column proxy_datum.USER
	 * @param user  the value for proxy_datum.USER
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public void setUser(String user) {
		this.user = user;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column proxy_datum.PASSWORD
	 * @return  the value of proxy_datum.PASSWORD
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column proxy_datum.PASSWORD
	 * @param password  the value for proxy_datum.PASSWORD
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column proxy_datum.SUCCESS_COUNT
	 * @return  the value of proxy_datum.SUCCESS_COUNT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public Integer getSuccessCount() {
		return successCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column proxy_datum.SUCCESS_COUNT
	 * @param successCount  the value for proxy_datum.SUCCESS_COUNT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public void setSuccessCount(Integer successCount) {
		this.successCount = successCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column proxy_datum.FAILURE_COUNT
	 * @return  the value of proxy_datum.FAILURE_COUNT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public Integer getFailureCount() {
		return failureCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column proxy_datum.FAILURE_COUNT
	 * @param failureCount  the value for proxy_datum.FAILURE_COUNT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public void setFailureCount(Integer failureCount) {
		this.failureCount = failureCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column proxy_datum.STATUS
	 * @return  the value of proxy_datum.STATUS
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column proxy_datum.STATUS
	 * @param status  the value for proxy_datum.STATUS
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column proxy_datum.CREATED_AT
	 * @return  the value of proxy_datum.CREATED_AT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column proxy_datum.CREATED_AT
	 * @param createdAt  the value for proxy_datum.CREATED_AT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column proxy_datum.UPDATED_AT
	 * @return  the value of proxy_datum.UPDATED_AT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column proxy_datum.UPDATED_AT
	 * @param updatedAt  the value for proxy_datum.UPDATED_AT
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof ProxyDatum)) {
			return false;
		}
		ProxyDatum other = (ProxyDatum) that;
		return this.getId() == null ? other == null
				: this.getId().equals(other.getId()) && this.getHost() == null ? other == null
						: this.getHost().equals(other.getHost())
								&& this.getPort() == null ? other == null
								: this.getPort().equals(other.getPort())
										&& this.getUser() == null ? other == null
										: this.getUser()
												.equals(other.getUser())
												&& this.getPassword() == null ? other == null
												: this.getPassword().equals(
														other.getPassword())
														&& this.getSuccessCount() == null ? other == null
														: this.getSuccessCount()
																.equals(other
																		.getSuccessCount())
																&& this.getFailureCount() == null ? other == null
																: this.getFailureCount()
																		.equals(other
																				.getFailureCount())
																		&& this.getStatus() == null ? other == null
																		: this.getStatus()
																				.equals(other
																						.getStatus())
																				&& this.getCreatedAt() == null ? other == null
																				: this.getCreatedAt()
																						.equals(other
																								.getCreatedAt())
																						&& this.getUpdatedAt() == null ? other == null
																						: this.getUpdatedAt()
																								.equals(other
																										.getUpdatedAt());
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	@Override
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getHost() != null) {
			hash *= getHost().hashCode();
		}
		if (getPort() != null) {
			hash *= getPort().hashCode();
		}
		if (getUser() != null) {
			hash *= getUser().hashCode();
		}
		if (getPassword() != null) {
			hash *= getPassword().hashCode();
		}
		if (getSuccessCount() != null) {
			hash *= getSuccessCount().hashCode();
		}
		if (getFailureCount() != null) {
			hash *= getFailureCount().hashCode();
		}
		if (getStatus() != null) {
			hash *= getStatus().hashCode();
		}
		if (getCreatedAt() != null) {
			hash *= getCreatedAt().hashCode();
		}
		if (getUpdatedAt() != null) {
			hash *= getUpdatedAt().hashCode();
		}
		return hash;
	}
}