package org.shirdrn.tinyframework.proxy.database.dao;

import java.util.List;
import org.shirdrn.tinyframework.proxy.database.model.ProxyDatum;
import org.shirdrn.tinyframework.proxy.database.model.ProxyDatumExample;

public interface ProxyDatumDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	int countByExample(ProxyDatumExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	int deleteByExample(ProxyDatumExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	Integer insert(ProxyDatum record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	Integer insertSelective(ProxyDatum record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	List<ProxyDatum> selectByExample(ProxyDatumExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	ProxyDatum selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	int updateByExampleSelective(ProxyDatum record, ProxyDatumExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	int updateByExample(ProxyDatum record, ProxyDatumExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	int updateByPrimaryKeySelective(ProxyDatum record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table proxy_datum
	 * @ibatorgenerated  Sun Feb 03 16:49:12 CST 2013
	 */
	int updateByPrimaryKey(ProxyDatum record);
}